Running game tag
PatrickRose/omega-website pull request #262
Opened 2022-11-13 23:00 UTC by franziskas1981

add a tag for a running game so I'm no longer confused

2022-11-13 23:21 UTC, PatrickRose commented
This is still pretty noisy, but I'm just about to pull a `.prettier` config together which might help.

I _think_ I can rebase your branch to include that, so I'll do that first

2022-11-14 00:00 UTC, PatrickRose requested changes
Quick review done :) A couple of changes if that's alright?

Since I've mucked with your branch, you probably want to do

```
$ git checkout runningGameTag
$ git fetch
$ git reset --hard origin/runningGameTag
```

Or 

```
$ git checkout develop
$ git fetch
$ git branch -D runningGameTag
$ git checkout runningGameTag
```

2022-11-14 00:20 UTC, franziskas1981 commented on src/pages/games/index.tsx
> +                    {getJSDateFromOmegaDate(props.date) < currentDate ? (
Yep... Will look at this tomorrow  and change it :)

2022-11-14 02:02 UTC, franziskas1981 commented on src/pages/games/index.tsx
> +                    {getJSDateFromOmegaDate(props.date) < currentDate ? (
![image](https://user-images.githubusercontent.com/34717874/201559788-7b8eac18-3890-4ecb-bcfa-327048928a00.png)

2022-11-17 21:06 UTC, franziskas1981 commented
requested changes made.

2022-11-17 23:16 UTC, franziskas1981 commented
done... :P

2022-11-17 23:26 UTC, PatrickRose approved these changes

2022-11-17 23:28 UTC, merged